import "../scss/reset.scss";
import "../scss/fonts.scss";
import "../scss/generic-style.scss"
//import "../scss/buttons.scss";
//import "../scss/header.scss";
import "../scss/main-img2/scss"
//import "../scss/main-img.scss";
//import "../scss/push.scss";
//import "../scss/products.scss";
//import "../scss/customer-reviews.scss";
