import "../scss/reset.scss";
import "../scss/fonts.scss";
import "../scss/generic-style.scss";
import "../scss/header.scss";
import "../scss/header-mobile.scss";
import "../scss/main-img-test.scss";
import "../scss/campaign.scss";
import "../scss/products.scss";
import "../scss/who-for.scss";
import "../scss/montessori.scss";
import "../scss/pro-part.scss";
import "../scss/presentation-laurie.scss";
import "../scss/values.scss";
import "../scss/reviews.scss";
import "../scss/sponsors-contact.scss";
import "../scss/footer.scss";
import "../scss/about.scss"